apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: books-app-namespace
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/books"
  SPRING_DATASOURCE_USERNAME: "postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: books-app-namespace
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: YWRtaW4=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-app-deployment
  namespace: books-app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: books-application
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: books-application
    spec:
      containers:
        - name: books-application
          image: jtrpkovska/books-application:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SPRING_DATASOURCE_PASSWORD
